# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: mind-os
description: This is my personal OS image.
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest 

modules:
  - type: kargs
    kargs:
      - modprobe.blacklist=serial8250
      - serial8250.nr_uarts=0
      - console=tty0
  
  - type: files
    files:
      - source: system
        destination: /
  
  - type: systemd
    system:
      custom:
        - name: flatpak-system-update.service
          enabled: true
          drop-in: true
          content: |
            [Unit]
            Before=
            [Service]
            Nice=19
            IOSchedulingClass=best-effort

        - name: fedora-atomic-desktop-appstream-cache-refresh.service
          enabled: true
          drop-in: true
          content: |
            [Unit]
            Before=
            [Service]
            Nice=19

        - name: NetworkManager-wait-online.service
          enabled: true
          drop-in: true
          content: |
            [Service]
            ExecStart=
            ExecStart=/usr/bin/nm-online -s -q --timeout=5

        - name: flatpak-system-update.timer
          enabled: true
          content: |
            [Unit]
            Description=Update Flatpaks long after boot
            [Timer]
            OnBootSec=15m
            RandomizedDelaySec=5m
            Persistent=true
            [Install]
            WantedBy=timers.target

        - name: fedora-atomic-desktop-appstream-cache-refresh.timer
          enabled: true
          content: |
            [Unit]
            Description=Refresh Appstream Cache long after boot
            [Timer]
            OnBootSec=20m
            RandomizedDelaySec=5m
            Persistent=true
            [Install]
            WantedBy=timers.target

        - name: system-flatpak-setup.service
          enabled: true
          content: |
            [Service]
            Nice=19
            IOSchedulingClass=best-effort
            IOSchedulingPriority=7
  
  - type: akmods
    install:
      - wl

  - type: dnf
    repos:
      copr:
        - atim/starship
    install:
      packages:
        - starship
    remove:
      packages:
        - firefox
        - firefox-langpacks

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - io.gitlab.librewolf-community
      - scope: user

  - type: initramfs
  - type: signing
